baseURL = 'https://heguang259.github.io/'
languageCode = 'zh-CN'
defaultContentLanguage = 'zh'
title = '心照笔记'
theme = 'hugo-PaperMod'

[pagination]
  pagerSize = 10

[taxonomies]
  category = 'categories'
  tag = 'tags'

[outputs]
  home = ['HTML', 'RSS', 'JSON']

[params]
  mainSections = ["posts"]
  defaultTheme = 'auto'
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowRssButtonInSectionTermList = true
  ShowAllPagesInArchive = true
  ShowPageNums = true
  ShowToc = true

[[menu.main]]
  name = '关于'
  url = 'about'
  weight = 1

[[menu.main]]
  name = '归档'
  url = 'archives'
  weight = 2

[[menu.main]]
  name = '搜索'
  url = 'search'
  weight = 3

[[menu.main]]
  name = '分类'
  url = 'categories'
  weight = 4

[[menu.main]]
  name = '标签'
  url = 'tags'
  weight = 5

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true
